// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AiMlDocumentDataSlicesSlice = never;

/**
 * Item in *AI/ML → AI/Ml Steps*
 */
export interface AiMlDocumentDataAiStepsItem {
  /**
   * Title field in *AI/ML → AI/Ml Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Icon field in *AI/ML → AI/Ml Steps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *AI/ML → AI/Ml Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *AI/ML → AI/ML Signs*
 */
export interface AiMlDocumentDataAiSignsItem {
  /**
   * Title field in *AI/ML → AI/ML Signs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AI/ML → AI/ML Signs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *AI/ML → AI/ML Signs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *AI/ML → Benefits*
 */
export interface AiMlDocumentDataBenefitsItem {
  /**
   * Title field in *AI/ML → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AI/ML → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *AI/ML → Benefits*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Item in *AI/ML → Examples*
 */
export interface AiMlDocumentDataExamplesItem {
  /**
   * Title field in *AI/ML → Examples*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *AI/ML → Examples*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *AI/ML → Examples*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *AI/ML → Content*
 */
export interface AiMlDocumentDataWhyUsListItem {
  /**
   * Title field in *AI/ML → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_list[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AI/ML → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_list[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Content for AI/ML documents
 */
interface AiMlDocumentData {
  /**
   * Hero Video field in *AI/ML*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.hero_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *AI/ML*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AiMlDocumentDataSlicesSlice> /**
   * Meta Title field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ai_ml.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ai_ml.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Data Science field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.data_science
   * - **Tab**: AI/ML
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  data_science: prismic.KeyTextField /**
   * What Is AI field in *AI/ML*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.what_is_ai
   * - **Tab**: What is AI/ML
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  what_is_ai: prismic.KeyTextField /**
   * AI/Ml Steps field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_steps[]
   * - **Tab**: Steps
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  ai_steps: prismic.GroupField<Simplify<AiMlDocumentDataAiStepsItem>> /**
   * AI/ML Signs field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.ai_signs[]
   * - **Tab**: Signs
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  ai_signs: prismic.GroupField<Simplify<AiMlDocumentDataAiSignsItem>> /**
   * Benefits field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.benefits[]
   * - **Tab**: Benefits
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  benefits: prismic.GroupField<Simplify<AiMlDocumentDataBenefitsItem>> /**
   * Examples field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.examples[]
   * - **Tab**: Examples
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  examples: prismic.GroupField<Simplify<AiMlDocumentDataExamplesItem>> /**
   * Image field in *AI/ML*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_image
   * - **Tab**: Why Us
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  why_us_image: prismic.ImageField<never>;

  /**
   * Content field in *AI/ML*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: ai_ml.why_us_list[]
   * - **Tab**: Why Us
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  why_us_list: prismic.GroupField<Simplify<AiMlDocumentDataWhyUsListItem>>;
}

/**
 * AI/ML document from Prismic
 *
 * - **API ID**: `ai_ml`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AiMlDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AiMlDocumentData>, "ai_ml", Lang>;

type HomeDocumentDataSlicesSlice = never;

/**
 * Item in *Home → Questions*
 */
export interface HomeDocumentDataQuestionsItem {
  /**
   * Title field in *Home → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.questions[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Answer field in *Home → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Item in *Home → Expertise*
 */
export interface HomeDocumentDataExpertiseItem {
  /**
   * Title field in *Home → Expertise*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *Home → Expertise*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Icon field in *Home → Expertise*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Url field in *Home → Expertise*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;
}

/**
 * Item in *Home → Engagement*
 */
export interface HomeDocumentDataEngagementItem {
  /**
   * Title field in *Home → Engagement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Info field in *Home → Engagement*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Image field in *Home → Engagement*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Home → Case Studies*
 */
export interface HomeDocumentDataCaseStudiesItem {
  /**
   * Title field in *Home → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slug field in *Home → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Info field in *Home → Case Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;

  /**
   * Image field in *Home → Case Studies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *Home → Case Studies*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Item in *Home → Why Cards*
 */
export interface HomeDocumentDataWhyCardsItem {
  /**
   * Icon field in *Home → Why Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.why_cards[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Content field in *Home → Why Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.why_cards[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Hero Video field in *Home*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Questions field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.questions[]
   * - **Tab**: Banner
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  questions: prismic.GroupField<Simplify<HomeDocumentDataQuestionsItem>> /**
   * Expertise field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.expertise[]
   * - **Tab**: Expertise
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  expertise: prismic.GroupField<Simplify<HomeDocumentDataExpertiseItem>> /**
   * Engagement field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.engagement[]
   * - **Tab**: Engagement
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  engagement: prismic.GroupField<Simplify<HomeDocumentDataEngagementItem>> /**
   * Case Studies field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.case_studies[]
   * - **Tab**: Case Studies
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  case_studies: prismic.GroupField<
    Simplify<HomeDocumentDataCaseStudiesItem>
  > /**
   * About Content field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.about_content
   * - **Tab**: About Us
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  about_content: prismic.RichTextField;

  /**
   * Why Cards field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.why_cards[]
   * - **Tab**: About Us
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  why_cards: prismic.GroupField<Simplify<HomeDocumentDataWhyCardsItem>>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = AiMlDocument | HomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AiMlDocument,
      AiMlDocumentData,
      AiMlDocumentDataSlicesSlice,
      AiMlDocumentDataAiStepsItem,
      AiMlDocumentDataAiSignsItem,
      AiMlDocumentDataBenefitsItem,
      AiMlDocumentDataExamplesItem,
      AiMlDocumentDataWhyUsListItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomeDocumentDataQuestionsItem,
      HomeDocumentDataExpertiseItem,
      HomeDocumentDataEngagementItem,
      HomeDocumentDataCaseStudiesItem,
      HomeDocumentDataWhyCardsItem,
      AllDocumentTypes,
    };
  }
}
