// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./CallToAction")),
  multiple_slice: dynamic(() => import("./MultipleSlice")),
  navigation_slice: dynamic(() => import("./NavigationSlice")),
  slice1: dynamic(() => import("./Slice1")),
  slice2: dynamic(() => import("./Slice2")),
  slice3: dynamic(() => import("./Slice3")),
  slice4: dynamic(() => import("./Slice4")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  title_with_analytics: dynamic(() => import("./Features")),
  title_with_button: dynamic(() => import("./Hero")),
  title_with_card_carousel: dynamic(() => import("./Carousel")),
  title_with_cards: dynamic(() => import("./Cards")),
  title_with_expertise: dynamic(() => import("./Expertise")),
  title_with_steps: dynamic(() => import("./Steps")),
  title_with_text: dynamic(() => import("./TitleWithText")),
};
