// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./CallToAction")),
  image_tiles: dynamic(() => import("./ImageTiles")),
  multiple_slice: dynamic(() => import("./MultipleSliceWithLinkAndLabel")),
  navigation_slice: dynamic(() => import("./NavigationSlice")),
  slice1: dynamic(() => import("./SliceWithImageOnly")),
  slice2: dynamic(() => import("./SliceWithImageAndRichTextTitle")),
  slice3: dynamic(
    () => import("./SliceWithImageRichTextTitleAndRichTextDescritpion"),
  ),
  slice4: dynamic(() => import("./SliceWithImageRichTextTitleAndNormalText")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  text_with_image_group: dynamic(() => import("./TextWithImageGroup")),
  text_with_title: dynamic(() => import("./TextWithTitle")),
  tiles: dynamic(() => import("./Tiles")),
  title_with_analytics: dynamic(() => import("./Features")),
  title_with_badge: dynamic(() => import("./TitleWithBadge")),
  title_with_button: dynamic(() => import("./Hero")),
  title_with_card_carousel: dynamic(() => import("./Carousel")),
  title_with_cards: dynamic(() => import("./Cards")),
  title_with_expertise: dynamic(() => import("./Expertise")),
  title_with_steps: dynamic(() => import("./Steps")),
  title_with_text: dynamic(() => import("./TitleWithText")),
};
